output "manager_servers_ips" {
  description = "Manager servers public IPv4 addresses"
  value = {
    for server in hcloud_server.managers :
    server.name => server.ipv4_address
  }
}

output "manager_servers_internal_ips" {
  description = "Manager servers internal IPv4 addresses"
  value = {
    for i, server in hcloud_server.managers :
    server.name => server
  }
}

output "worker_servers_ips" {
  description = "Worker servers public IPv4 addresses"
  value = {
    for server in hcloud_server.workers :
    server.name => server
  }
}

output "worker_servers_internal_ips" {
  description = "Worker servers internal IPv4 addresses"
  value = {
    for i, server in hcloud_server.workers :
    server.name => server
  }
}

output "nfs_server_ips" {
  description = "NFS servers public IPv4 addresses"
  value = {
    for server in hcloud_server.nfs :
    server.name => server.ipv4_address
  }
}

# Feed each id into prod/ansible/inventory [nfs] drbd_volume_id=<id> (NOT the legacy nfs volume).
output "nfs_drbd_volume_ids" {
  description = "DRBD backing volume ids for the NFS HA pair (nfs-drbd-0/1)"
  value = {
    for v in hcloud_volume.nfs_drbd :
    v.name => v.id
  }
}

# The whole ansible/inventory, rendered. `./up inventory` writes it with:
#   terraform output -raw ansible_inventory > ../ansible/inventory
#
# Private IPs are read back off each server's network block rather than recomputed from the IP plan,
# so this can't drift from main.tf. Copying these by hand was the one manual seam in the build.
output "ansible_inventory" {
  description = "Rendered ansible/inventory — see ./up inventory"
  value = join("\n", concat(
    [
      "# GENERATED by `./up inventory` from terraform state. Do not hand-edit — re-run ./up inventory.",
      "",
      "[backoffice]",
      hcloud_server.backoffice_nat.ipv4_address,
      "",
      "[lb_main]",
    ],
    [for i, s in hcloud_server.lbs : "${s.ipv4_address} role=${i == 0 ? "master" : "backup"}"],
    [
      "",
      "# The real floating IP keepalived aliases and failover.sh moves. Sourced from terraform so it",
      "# can't drift from the DNS records pointing at it (cloudflare.tf uses the same address).",
      "[lb_main:vars]",
      "floating_ip=${hcloud_floating_ip.lb_main.ip_address}",
    ],
    ["", "[k0s_controllers]"],
    [for i, s in hcloud_server.managers : "${one(s.network).ip}${i == 0 ? " role=leader" : ""}"],
    ["", "[k0s_workers]"],
    [for s in hcloud_server.workers : one(s.network).ip],
    [
      "",
      "# VIP 10.0.0.199 floats between the pair. drbd_volume_id = the dedicated nfs-drbd-N volume.",
      "[nfs]",
    ],
    [for i, s in hcloud_server.nfs :
      "${one(s.network).ip} role=${i == 0 ? "master" : "backup"} hostname=${s.name} drbd_priority=${i == 0 ? 200 : 100} drbd_volume_id=${hcloud_volume.nfs_drbd[i].id}"
    ],
    [
      "",
      "# Diskless DRBD quorum tiebreaker (no data, no NFS, no keepalived) — the backoffice box on its",
      "# private IP. Third vote, so a partitioned NFS node loses quorum instead of diverging.",
      "[nfs_tiebreaker]",
      "${one(hcloud_server.backoffice_nat.network).ip} hostname=${hcloud_server.backoffice_nat.name} drbd_diskless=true",
      "",
      "# All DRBD members (pair + tiebreaker) — used to render the shared r0.res on every node.",
      "[nfs_cluster:children]",
      "nfs",
      "nfs_tiebreaker",
      "",
      "[db]",
    ],
    [for s in hcloud_server.database_servers : "${one(s.network).ip} hostname=${s.name}"],
    [""],
  ))
}
